name: Reusable Windows MSI

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: zip installer
    timeout-minutes: 60
    runs-on: windows-2022
    env:
      ARCH: windows-2022
      IncludeFreethreaded: true
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Build CPython installer
      run: ./Tools/msi/build.bat --doc -"${ARCH}"
      shell: bash
