name: Reusable Windows MSI

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: zip installer
    timeout-minutes: 60
    runs-on: windows-2022
    env:
      ARCH: amd64
      IncludeFreethreaded: true
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Build CPython installer
      run: ./Tools/msi/buildrelease.bat -"${ARCH}"
      shell: bash
    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-msi
        path: ./PCBuild/**/&.zip
